### ISSUE TITLE
@import is removed

### ISSUE THREAD

**Issue by YusukeHirao** [buildingblocks/grunt-combine-media-queries#13]
The line include `@import` is removed from the code like an example.

``` css
@import url("http://fonts.googleapis.com/css?family=Electrolize");
body {
  font-family: Electrolize;
}
```

->

``` css
body {
  font-family: Electrolize;
}
```
