### ISSUE TITLE
Preservation of original CSS

### ISSUE THREAD

**Issue by thomasdobber** [buildingblocks/grunt-combine-media-queries#2]
At the moment comments are stripped from the CSS and indention is done automatically.

We might have to consider to stop using a CSS parser and instead grab all content within media queries differently (maybe regex?) and this way include nested keyframes and comments and leave original indention intact.

**Comment by tomByrer** [comment]
Workarounds:
- users can follow up with your favorite CSS beautifier or `.editorconfg`.
- this project use [mensch](https://github.com/brettstimmerman/mensch#comments) to preserve _most_ comments.  It can also preserve position of column, so cloning reproduction is semi-possible.

REGEX or if-then-else or switch-case may seem easy at first:

``` css
@media (min-width: 768px) {
  .container {
    width: 750px;
  }
}
```

but will require more programming than you think to handle cases like this:

``` css
@media (min-width:768px){.container {
    width: 750px;
  }}
@media
  (min-width: 992px)
    {
      .container {
        width: 970px;
      }
    }
@media (min-width: 1200px) { /* comment in middle */ .container {
 /* start of line comment */   width: 1170px;
  }
}
```
