### ISSUE TITLE
Generate warning for reordering breakage

### ISSUE THREAD

**Issue by splondike** [buildingblocks/grunt-combine-media-queries#32]
There's at least one situation where CMQ can change the ordering of rules. Consider the following (we had some SCSS mixins which compiled to essentially this):

``` CSS
.my-class, .other-class {
    color: red;
}
@media(min-width: 100px) {
    .my-class, .other-class {
        color: blue;
    }
}

.my-class {
    color: green;
}
@media(min-width: 100px) {
    .my-class {
        width: 150px;
    }
}
```

CMQ will put both the media query blocks at the end of the file. As a consequence if the screen width >= 100px 'my-class' will be blue. Without CMQ the same screen size would result in green.

This is of course how CMQ is meant to work, but it would be nice to print a warning message in this case. It doesn't look like this would be easy unfortunately, as you would need to trace through the resultant attributes for each select/media query pair and see if anything differed between the original and changed file.
